apiVersion: apps/v1
kind: Deployment
metadata:
    name: wil-playground-deployment
    labels:
        app: app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app
    template:
        metadata:
            labels:
                app: app
        spec:
            containers:
                - name: app
                  image: wil42/playground:v2
                  ports:
                      - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
    name: wil-playground-service
spec:
    selector:
        app: app
    ports:
        - name: app-port
          protocol: TCP
          port: 80
          targetPort: 8888
    type: ClusterIP
